FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests -Dcheckstyle.skip
FROM openjdk:17-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar .
CMD ["java", "-jar", "*.jar"]